Vagrant.configure(2) do |config|
    config.vm.box = "vagrant-kubernetes"

    # Disabled VirtualBox Guest updates
    if Vagrant.has_plugin?("vagrant-vbguest")
      config.vbguest.auto_update = false
    end
end
